// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseThemeToggle: typeof import('./components/ui/BaseThemeToggle.vue')['default']
    LanguageSelector: typeof import('./components/ui/LanguageSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('@headlessui/vue')['Switch']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    ThePersonalCardResume: typeof import('./components/ThePersonalCardResume.vue')['default']
    TheSoftwareDomain: typeof import('./components/TheSoftwareDomain.vue')['default']
  }
}
